version: 2

models:
  - name: dim_listings_cleansed
    tests:
      - minimum_row_count:
          min_row_count: 100
    columns:

      - name: listing_id
        tests:
          - unique
          - not_null

    columns:
      - name: host_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id
              config:
                severity: warn

      - name: room_type
        tests:
          - accepted_values:
              values:
                - "Entire home/apt"
                - "Private room"
                - "Shared room"
                - "Hotel room"
